spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
    username: sa
    password:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
